trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: |
    chmod u+x hyperexecute
    ./hyperexecute.exe --user $(LT_USERNAME) --key $(LT_ACCESS_KEY) --config yaml/win/junit_hyperexecute_autosplit_sample.yaml --env stage --verbose
  displayName: 'run HE test'
