name: hyperexecute_run
on: push
jobs:
  golangci:
    name: hyperexecute grid testing
    runs-on: macos-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'download binary'
        run: wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute

      - name: 'provide access to file'
        run: chmod u+x hyperexecute

      - name: run test
        run: ./hyperexecute --user himanshigupta --key mieWXJBENSSzM4OZ8Lav439gUxq9pYmKKGlf7yxigqpI37CIcN --config yaml/win/junit_hyperexecute_autosplit_sample.yaml --env stage --verbose
